# Generated by Django 3.0.8 on 2020-09-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200903_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price']},
        ),
    ]
