# Generated by Django 3.0.8 on 2020-09-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='credits',
            new_name='credit',
        ),
    ]
